blank_issues_enabled: false
contact_links:
  - name: Praxel.ai Community Support
    url: https://github.com/praxelai/community/discussions
    about: Please ask and answer questions here.
  - name: Praxel.ai Security Reports
    url: https://praxel.ai
    about: Please report security vulnerabilities to support@praxel.ai
